name: GCP-PUB/SUB for spinnaker

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Select an option'
        required: true
        type: choice
        options:
          - Start
          - Stop
          - Resume

jobs:
  publish-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout your code if necessary
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: proj-notification-416405
          export_default_credentials: true

      - name: Publish message to Pub/Sub
        run: |
          gcloud pubsub topics publish Email-notify --message='{"access": "true"}'
