name: Trigger from docker publish

on:
 push: 
   branches: 
     - "master"
     
# env:
#   secure_data: ${{ toJson(fromJson(secrets.MY_SECRET)) }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "${{ secrets.NEW_SECRET }}"
      - name: Extract Docker credentials
        run: echo '${{ secrets.NEW_SECRET }}' > ~/docker_credentials.json
  
      - name: Login to Docker registry
        run: |
            echo "$(cat /docker_credentials.json)" | jq -r '.username' > /docker_username
            echo "$(cat /docker_credentials.json)" | jq -r '.password' > /docker_password
