name: Docker Publish

on:
  push:
    branches:
      - master  

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_ACCESS_TOKEN: ${{secrets.DOCKER_ACCESS_TOKEN}}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ env.DOCKER_ACCESS_TOKEN }}" | docker login --username ${{env.DOCKER_USERNAME}} --password-stdin

      - name: Build and tag Docker image
        run: docker build . -t ${{env.DOCKER_USERNAME}}/sample-node-app:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{env.DOCKER_USERNAME}}/sample-node-app:latest
