name: Trigger from docker publish

on:
 push: 
   branches: 
     - "master"
     
# env:
#   secure_data: ${{ toJson(fromJson(secrets.MY_SECRET)) }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "${{ secrets.NEW_SECRET }}"
      - name: Fetch value from JSON
        id: convert
        run: |
          # Construct JSON object
          JSON_OBJECT=${{ secrets.NEW_SECRET }}
          echo "::set-output name=json_data::$JSON_OBJECT"
          
      - name: Use JSON data
        run: |
          USERNAME=$(echo "${{ steps.convert.outputs.json_data }}" | jq -r '.username')
          PASSWORD=$(echo "${{ steps.convert.outputs.json_data }}" | jq -r '.password')
