name: Trigger from docker publish

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - 'true'
          - 'false'
     
env:
   DOCKER_USERNAME: ${{ fromJson(secrets.NEW_SECRET).username }}
   DOCKER_PASSWORD: ${{ fromJson(secrets.NEW_SECRET).password }}
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check input and run if true
        if: ${{ github.event.inputs.run-workflow == 'true' }}
        run: |
          echo "Workflow is running."
          
      - name: Skipped if input is no
        if: ${{ github.event.inputs.run-workflow == 'false' }}
        run: |
          echo "Workflow is skipped."
          exit 0  # Exit the job successfully
          
      - name: Print message
        run: echo "${{ secrets.NEW_SECRET }}"
      - name: Extract Docker credentials
        run: echo '${{ secrets.NEW_SECRET }}' > ~/docker_credentials.json
  
      - name: Extract credentials
        run: |
            echo "$(cat ~/docker_credentials.json)" | jq -r '.username' > ~/docker_username
            echo "$(cat ~/docker_credentials.json)" | jq -r '.password' > ~/docker_password
            echo $(cat ~/docker_username)
            echo "$DOCKER_USERNAME"
