name: Docker Publish

on:
  push:
    branches:
      - master  

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_ACCESS_TOKEN: ${{secrets.DOCKER_ACCESS_TOKEN}}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
      - name: Build and tag Docker image
        run: docker build . -t ${{env.DOCKER_USERNAME}}/sample-node-app:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{env.DOCKER_USERNAME}}/sample-node-app:latest

      - name: Capture Image Digest
        id: digest
        run: |
          DIGEST=$(docker inspect --format '{{index .RepoDigests 0}}' ${{env.DOCKER_USERNAME}}/sample-node-app:latest)
          echo "$DIGEST"
          echo "Image Digest: $DIGEST" > image_digest.txt

      - name: Store Image Digest in GitHub Repo
        uses: actions/upload-artifact@v4
        with:
          name: image-digest
          path: image_digest.txt
      - name: Commit and Push Image Digest File
        run: |
          git config --global user.email "panchalharsh0207@gmail.com"
          git config --global user.name "HaRsH020772"
          git add image_digest.txt
          git commit -m "Add image digest file"
          git remote set-url origin "https://${{ secrets.ACTION_SECRET }}@github.com/HaRsH020772/sample-node-app.git"
          git push origin main

