name: Docker Publish

on:
  push:
    branches:
      - master  

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_ACCESS_TOKEN: ${{secrets.DOCKER_ACCESS_TOKEN}}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
      - name: Build and tag Docker image
        run: docker build . -t ${{env.DOCKER_USERNAME}}/sample-node-app:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{env.DOCKER_USERNAME}}/sample-node-app:latest

      - name: Fetch image digest
        run: |
          digest=$(docker inspect --format='{{index .RepoDigests 0}}' ${{env.DOCKER_USERNAME}}/sample-node-app:latest)
          echo "DIGEST: $digest" >> digest.txt

      - name: Commit and push digest file
        uses: EndBug/add-and-commit@v7
        with:
          add: digest.txt
          message: "Update image digest"
          branch: master

