name: Trigger from docker publish

on:
 push: 
   branches: 
     - "master"
     
# env:
#   secure_data: ${{ toJson(fromJson(secrets.MY_SECRET)) }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "${{ secrets.NEW_SECRET }}"
      # - name: Set secure environment variable
        # env:
          # SECURE_DATA: ${{ toJson(fromJson(secrets.NEW_SECRET)) }}
      - name: Another message
        run: echo "${{ env.SECURE_DATA.username }}"
