name: Docker Publish

on:
#  push:
 #   branches:
  #    - "master"
  workflow_dispatch:
    inputs:
      choice:
        description: 'Select an option'
        required: true
        type: choice
        options:
          - Name 1
          - Name 2
          - Name 3
      name:
        description: Enter your name to proceed
        type: string
        required: true
      
env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_ACCESS_TOKEN: ${{secrets.DOCKER_ACCESS_TOKEN}}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: greeting to user
        run: |
         echo " Good Morning  ${{ github.event.inputs.choice}} !"
         echo " Name field : ${{github.event.inputs.name}}"
       
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
      - name: Build and tag Docker image
        run: docker build . -t ${{env.DOCKER_USERNAME}}/sample-node-app

      - name: Push Docker image to Docker Hub
        run: docker push ${{env.DOCKER_USERNAME}}/sample-node-app

      - name: Get Docker image digest
        id: get_digest
        run: |
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{env.DOCKER_USERNAME}}/sample-node-app)
          echo $DIGEST > image_digest.txt
          echo "::set-output name=digest::$DIGEST"

      - name: Upload image digest as artifact
        uses: actions/upload-artifact@v2
        with:
          name: image-digest
          path: image_digest.txt

  trigger_workflow2:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Trigger Workflow 2
        uses: actions/github-script@v4
        with:
          script: |
            const { data: workflows } = await github.actions.listRepoWorkflows({ owner: context.repo.owner, repo: context.repo.repo });
            const workflow2 = workflows.workflows.find(workflow => workflow.path === '.github/workflows/main2.yml');
            await github.actions.createWorkflowDispatch({
              workflow_id: workflow2.id
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # - name: Capture Image Digest
      #   id: digest
      #   run: |
      #     DIGEST=$(docker inspect --format '{{index .RepoDigests 0}}' ${{env.DOCKER_USERNAME}}/sample-node-app:latest)
      #     echo "Image Digest: $DIGEST" > $GITHUB_WORKSPACE/image_digest.txt
      #     cat $GITHUB_WORKSPACE/image_digest.txt
          
      # - name: Commit and Push Image Digest File
      #   run: |
      #     touch abc
      #     git config --global user.email "panchalharsh0207@gmail.com"
      #     git config --global user.name "HaRsH020772"
      #     git add $GITHUB_WORKSPACE/image_digest.txt
      #     git commit -m "Add image digest file"
      #     git push origin master
