name: Test matrix startegy

on:
  workflow_dispatch:
    inputs:
      versions:
        description: 'Add multiple versions (comma-separated)'
        required: true
        default: '1,2,3' 

jobs:
  test_versioning:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ split(inputs.versions, ',') }}  # Add more versions here as needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print the version text
        run: |
          echo "This is a version ${{matrix.version}}"
