# name: Test matrix startegy

# on:
#   workflow_dispatch:
#     inputs:
#       versions:
#         description: 'Add multiple versions (comma-separated)'
#         required: true
#         default: '1,2,3' 

# jobs:
#   test_versioning:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         version: ${{fromJson('['+github.event.inputs.versions+']')}}  # Add more versions here as needed

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Print the version text
#         run: |
#           echo "This is a version ${{matrix.version}}"

name: AWS-SNS

on:
#  push:
 #   branches:
  #    - "master"
   
  workflow_dispatch:
    inputs:
      choice:
        description: 'Select an option'
        required: true
        type: choice
        options:
          - Name 1
          - Name 2
          - Name 3
      name:
        description: Enter your name to proceed
        type: string
        required: true

# jobs:
#   publish-message:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3  # Checkout your code if necessary
#       - id: auth
#         name: Authenticate to GCP
#         uses: google-github-actions/auth@v2
#         with:
#           credentialsJson: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
#       - id: publish
#         name: Publish message
#         uses: miraliumre/actions-pubsub@v1  # Or another compatible action
#         with:
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
#           topic_name: Docker_registry  # Replace with your Pub/Sub topic name
#           message: '{"data": "Your message content"}' 

jobs:
  publish_to_pubsub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Service Account Key JSON
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Publish to Pub/Sub
        uses: miraliumre/actions-pubsub@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          topic_name: Docker_registry
          message: "Hello, world!"
