name: Trigger from docker publish

on:
#  push: 
 #   branches: 
  #    - "master"
  workflow_run:
   workflows: ["Docker Publish"]
   types: 
    - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Message from Trigger from docker publish"
